### PR TITLE
Fix alignment of "user region" icons (#265)

### PR DESCRIPTION
**Pull request by warpech**
I have created a clean fix for this problem, but sadly, it works only in Chrome. Is `:host` not supported in the polyfill?

Issue: #265

Any ideas @miyconst, @mmnosek?

2017-01-17 18_04_58-databaseeditor - microsoft visual studio

### CODE REVIEW

**Comment by mmnosek** [comment]
As we discussed: http://stackoverflow.com/questions/30599628/webcomponents-js-shadow-dom-host-selector-does-not-work-on-safari-and-firefox

I will also create an issue in UserAdmin to change a default size of the icon. It should be exactly the same as user avatar.

**Comment by warpech** [comment]
As said in the above link, `:host` selector is not supported by WC v0 polyfill so a custom script is needed. 

I have added the custom script in the above commit. Feel free to add it to other partials that use `:host`.

**Comment by warpech** [comment]
> I will also create an issue in CompositionEditor to change a default size of the icon. It should be exactly the same as user avatar.

Maybe let's handle this in the already existing PR: https://github.com/Starcounter/CompositionEditor/pull/4

**Comment by warpech** [comment]
I will evaluate one change in the above script - put the `<script>` inside `starcounter-composition`.

**Comment by warpech** [comment]
For some reason, a `<script>` inside `starcounter-composition` is not executed at all. I have created an issue: https://github.com/Starcounter/starcounter-include/issues/18

Also, I have pushed a simpler fix for the `:host` selector problem in the polyfill. See above.

**Pull request merged**
