### PR TITLE
Freeze inactive workspaces 215

### PR DESCRIPTION
**Pull request by joozek78**

### CODE REVIEW

**Comment by joozek78** [comment]
cc @warpech

**Comment by warpech** [comment]
Related issue #215

**Comment by chrhol** [comment]
Yes, I think this will work. The setting for `AutoRefreshBoundProperties` follows the setting for `ActiveWorkspace`

One thing is that we should remove setting the property to false in `Launcher_AcceptanceHelperOnePage.json.cs` ([L25](https://github.com/StarcounterPrefabs/Launcher/blob/5b0a1bd0fb439bd599edd1b5c9c7069df6e50071/test/Launcher_AcceptanceHelperOne/Launcher_AcceptanceHelperOnePage.json.cs#L25)) and `Launcher_AcceptanceHelperTwoPage.json.cs` ([L21-L22](https://github.com/StarcounterPrefabs/Launcher/blob/5b0a1bd0fb439bd599edd1b5c9c7069df6e50071/test/Launcher_AcceptanceHelperTwo/Launcher_AcceptanceHelperTwoPage.json.cs#L21-L22)) and leave it up to the launcher to decide when to disable the autoupdate. This only concerns the test though.

Can you remove those lines @joozek78?

**Comment by joozek78** [comment]
I removed them, merging

**Pull request merged**
